### ISSUE TITLE
handle error responses 

### ISSUE THREAD

**Issue by Abe404** [rohanorton/proto-jSend#3]
400, 500, 404, 401, 403

**Comment by rohanorton** [comment]
Ok. Fleshed out the spec a little bit:

We should implement a `jSend.error` method and a `jSend.fail` method that we can build further shortcut methods from (i.e. `jSend.notFound`, `jSend.serverError`, etc.)

## res.jSend.error
- This is for 5xx type errors (i.e. internal server error)
- I guess that the footprint would look like this:

``` js
/**
 * Send custom jSend "error" messages to client
 *
 * @param {Object} arguments - Object containing options for jSend.error
 * @param {Number} arguments.code - HTTP Status Code 5xx
 * @param {String} arguments.message - Message to be sent to the client
 * @param {Object} [arguments.data] - Object to be sent to the client
 */
res.jSend.error = function (arguments) {
  // ...
}
```
- Example usage:

``` js
res.jSend.error({
  code: 500,
  message: "Internal Server Error",
  data: new Error('Broke it!')
});
```

``` http
HTTP/1.1 500 Error
{
  "status": "error",
  "message": "Internal Server Error"
}
```
- A stack trace (or I guess, whatever you want to put in data) will also show on the data property when not in production environment for debugging purposes:

``` http
HTTP/1.1 500 Error
{
  "status": "error",
  "message": "Internal Server Error",
  "data": "Error: Broke it!\n    at Object.<anonymous> (/Users/foo/app.js:12:25)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Function.Module.runMain (module.js:501:10)\n    at startup (node.js:129:16)\n    at node.js:814:3"
}
```

## res.jSend Fail
- This is for 4xx type errors (i.e. bad request, unauthorised etc.)
- Footprint:

``` js
/**
 * Send custom jSend "fail" messages to client
 *
 * @param {Object} arguments - Object containing options for jSend.fail
 * @param {Number} arguments.code - HTTP Status Code 4xx
 * @param {Object} arguments.data - Object to be sent to the Client
 */
res.jSend.fail = function (arguments) {
   // ...
};
```
- Example usage:

``` js
res.jSend.error({
  code: 400,
  message: "Bad Request",
  data: {
    title: "Title property of type string is required"
  }
});
```

``` http
HTTP/1.1 400 Bad Request
{
  "status": "fail",
  "data": {
    "title": "Title property of type string is required"
  }
}
```
- Don't think that there's anything that we would want to add in debug mode, right??

**Comment by rohanorton** [comment]
Hm. Thinking about how to represent Error objects in JSON. Maybe it would be better to do something like this to increase clarity:

``` http
HTTP/1.1 500 Error
{
  "status": "error",
  "message": "Internal Server Error",
  "data": { 
    "message": "Error: Broke it!",
    "stack": [
      "at Object.<anonymous> (/Users/foo/app.js:12:25)",
      "at Module._compile (module.js:460:26)",
      "at Object.Module._extensions..js (module.js:478:10)",
      "at Module.load (module.js:355:32)",
      "at Function.Module._load (module.js:310:12)",
      "at Function.Module.runMain (module.js:501:10)",
      "at startup (node.js:129:16)",
      "at node.js:814:3"
    ]
  }
}
```

Thoughts?

**Comment by Abe404** [comment]
Yes, that all looks awesome.

**Comment by rohanorton** [comment]
Think we could implement the error thing sort of like this:

``` js
var err = new Error('Foo');
var trace = err.stack.split(/\n\s*/g);
var data = { message: trace.shift(), stack: trace };
```

(untested)

At least, this is first thing that comes to mind.
